config/routes.rb
AlterneticaCom::Application.routes.draw do
  get "home/index"
  resources :contents

  resources :categories

   root :to => "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_friendly_id :name , :use_slug => true
    validates_presence_of :name, :on => :create, :message => "No puede estar en blanco."
end

app/models/content.rb
class Content < ActiveRecord::Base
    has_friendly_id :title , :use_slug => true
    validates_presence_of :title,:short_content,:large_content, :on => :create, :message => "can't be blank"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.xml
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.xml
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.xml
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.xml
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to(@content, :notice => 'Content was successfully created.') }
        format.xml  { render :xml => @content, :status => :created, :location => @content }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.xml
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to(@content, :notice => 'Content was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @content.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.xml
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to(contents_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/categories/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.category.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :position, t("activerecord.attributes.category.position", :default => "Position"), :class => :label %>
    <%= f.text_field :position, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :cached_slug, t("activerecord.attributes.category.cached_slug", :default => "Cached slug"), :class => :label %>
    <%= f.text_field :cached_slug, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), categories_path, :class => "text_button_padding link_button" %>
</div>

app/views/categories/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_category_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Category</h2>
    <div class="inner">
      <%= form_for @category, :url => category_path(@category), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/categories/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_category_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Categories</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.category.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @categories.each do |category| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= category.id %>
          </td>
                    <td>
            <%= link_to category.name, category_path(category) %>
          </td>
                    <td>
            <%= category.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", category_path(category) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_category_path(category) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", category_path(category), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/categories/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", categories_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_category_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Category</h2>
    <div class="inner">
      <%= form_for :category, :url => categories_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/categories/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", category_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.category.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @category.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.category.position", :default => t("activerecord.labels.position", :default => "Position")) %>:</b>
          <%= @category.position %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.category.cached_slug", :default => t("activerecord.labels.cached_slug", :default => "Cached slug")) %>:</b>
          <%= @category.cached_slug %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_category_path(@category), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), category_path(@category), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/contents/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.content.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :short_content, t("activerecord.attributes.content.short_content", :default => "Short content"), :class => :label %>
    <%= f.text_area :short_content, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :large_content, t("activerecord.attributes.content.large_content", :default => "Large content"), :class => :label %>
    <%= f.text_area :large_content, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :category_id, t("activerecord.attributes.content.category_id", :default => "Category"), :class => :label %>
    <%= f.text_field :category_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :cached_slug, t("activerecord.attributes.content.cached_slug", :default => "Cached slug"), :class => :label %>
    <%= f.text_field :cached_slug, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), contents_path, :class => "text_button_padding link_button" %>
</div>

app/views/contents/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
   <li><%= link_to "#{t("web-app-theme.show", :default => "Categorias")}", '/categories/'%></li>
   <li><%= link_to "#{t("web-app-theme.show", :default => "Contenido")}", '/contents/' %></li>
  
  </ul>
</div>

app/views/contents/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_content_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Content</h2>
    <div class="inner">
      <%= form_for @content, :url => content_path(@content), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/contents/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Contents</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.content.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @contents.each do |content| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= content.id %>
          </td>
                    <td>
            <%= link_to content.title, content_path(content) %>
          </td>
                    <td>
            <%= content.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", content_path(content) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_content_path(content) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", content_path(content), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/contents/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Content</h2>
    <div class="inner">
      <%= form_for :content, :url => contents_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/contents/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", content_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.content.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @content.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.content.short_content", :default => t("activerecord.labels.short_content", :default => "Short content")) %>:</b>
          <%= @content.short_content %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.content.large_content", :default => t("activerecord.labels.large_content", :default => "Large content")) %>:</b>
          <%= @content.large_content %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.content.category_id", :default => t("activerecord.labels.category_id", :default => "Category")) %>:</b>
          <%= @content.category_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.content.cached_slug", :default => t("activerecord.labels.cached_slug", :default => "Cached slug")) %>:</b>
          <%= @content.cached_slug %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_content_path(@content), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), content_path(@content), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => '/layouts/sidebar') -%>

app/views/home/index.html.erb
<div class="block" id="block-text">  
  <div class="content">
    <h2 class="title">Index</h2>
    <div class="inner">
      <p class="first">
        Aplicacion para manejar el contenido de nuestro web.  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">pendiente diablo
      </p>
      <p> <span class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <p> <span class="gray">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <hr />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'layouts/sidebar') -%>

app/views/layouts/_sidebar.html.erb
<!--	ESTE ARCHIVO GENERALMENTE ESTA POR CADA GENERACION QUE HACEMOS CON EL RAILS G , PARA EL THEME , PERO LO HE 
INCLUIDO EN UN UNICO LAYOUT PARA HACER RENDER. ENTONCES CADA NUEVO MODULO QUE SE HAGA SERIA RECOMENDABLE 
LINKEARLO ACA DE LA FORMA QUE ESTAN HECHO ESTOS DOS.
-->
<div class="block notice">
  <h3>ultimos eventos</h3>
  <div class="content">
    <p>aqui vamos a ver que inventamos......</p>
<p><%= Time.now%></p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
   <li><%= link_to "#{t("web-app-theme.show", :default => "Categorias")}", '/categories/'%></li>
   <li><%= link_to "#{t("web-app-theme.show", :default => "Contenido")}", '/contents/' %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alternetica R.L aplicacion backend</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Alternetica R.L aplicacion backend</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
			   <li><%= link_to "#{t("web-app-theme.show", :default => "Categorias")}", '/categories/'%></li>
			   <li><%= link_to "#{t("web-app-theme.contenido", :default => "Contenido")}", '/contents/' %></li>
			   <li><%= link_to "#{t("web-app-theme.blog", :default => "Blog")}",  %></li>
			

        </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Alternetica R.L aplicacion backend.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>